version: "3.1"

services:
  db:
    image: postgres:latest
    volumes:
      - ./server/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER= "${DB_USER}"
      - POSTGRES_PASSWORD= "${DB_PASSWORD}"
    ports:
      - "5432:5432"
